# Site settings
title: Kelly Merckaert
email: kelly.merckaert@gmail.com
url: https://kmerckae.github.io/
description: "Personal website of Kelly Merckaert, researcher in robotics and control engineering, hobbyist photographer, and piano player."
keywords: "robotics, control, photography" #"your keywords, separated by commas"
skills: "Robotic Control Systems Engineer - Hobbyist Photographer - Pianist"
author: Kelly Merckaert

# Footer settings
footer:
  copyright: kmerckae
  location: Location
  social: Get in Touch #Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/kmerckae
  - title: linkedin
    url: https://www.linkedin.com/in/kellymerckaert
  - title: graduation-cap
    url: https://scholar.google.be/citations?hl=en&user=Pf600mUAAAAJ
  - title: instagram
    url: https://www.instagram.com/kellymerckaert

  

# Postal address (add as many lines as necessary)
address:
  - line: Based in Mechelen, Belgium
  # - line: Beverly Hills, CA 90210

# Credits content
credits: 'Made with <a href="https://jekyllrb.com/">Jekyll for GitHub</a>. The design is modified from the <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Theme</a>. '
#'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
